run:
  deadline: 10m
skip-dirs:
    - vendor
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
#    - errorlint
    - goconst
#    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
#    - interfacer
    - maligned
    - misspell
    - nakedret
#    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  exclude-rules:
    - path: tests/e2e
      linters:
        - golint
  #include:
  #  - EXC0002 # include "missing comments" issues from golint
  max-issues-per-linter: 0
  max-same-issues: 0
